import NavBar from "@src/components/layout/Navbar";
import NewsBar from "@src/components/layout/NewsBar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@css/layout/globals.css";
import "@css/layout/navbar.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Common components */}
        <NewsBar />
        <NavBar />

        {/* Container for page content */}
        <div className="pt-28 flex min-h-screen w-full shadow-lg flex-col">
          {children}
        </div>
      </body>
    </html>
  );
}
